### PR TITLE
Bump to v0.3

### PR DESCRIPTION
**Pull request by deppen8**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by deppen8** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
All green, should be mergeable. (I just tried to pin to `>= 0.3` because it's on PyPI and found it's not on conda-forge yet!)

**Comment by bsipocz** [comment]
@bmcfee and @sugatoray -  If you would find it to be helpful to have one more pair of hands on deck, I would be happy to be added as recipe maintainer (as part of my involvement with shepherding packages in the scientific-python org).

**Review by bmcfee — APPROVED** [review]
Lgtm!

**Comment by bmcfee** [comment]
@bsipocz thanks! And sure, it'd be great to have you added here.

**Comment by sugatoray** [comment]
@bsipocz Thank you for your contribution. We would be glad to have you as a co-maintainer. 

@bmcfee How would you suggest we add @bsipocz to the list of maintainers? Just update the meta.yaml file or otherwise?

**Comment by bmcfee** [comment]
> @bmcfee How would you suggest we add @bsipocz to the list of maintainers? Just update the meta.yaml file or otherwise?

Yeah, @bsipocz can add herself to the list and it's automatic upon merge.

**Comment by bsipocz** [comment]
> yeah, @bsipocz can add herself to the list and it's automatic upon merge.

I couldn't suggest change on the relevant line here, so it was quickest to do it was to ask the bot, see #8

**Comment by bmcfee** [comment]
Thanks again @bsipocz - both are merged now.

**Pull request merged**
