### PR TITLE
0.1 release

### PR DESCRIPTION
**Pull request by bmcfee**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bmcfee** [comment]
I also took the liberty of correcting a few things in the recipe file (URLs for the repo and version constraints)

**Comment by bmcfee** [comment]
@sugatoray could you give this a look?  Thanks!

**Comment by sugatoray** [comment]
@bmcfee Thank you for the PR. Would you like to be added as a maintainer as well?

**Comment by sugatoray** [comment]
Another set of eyeballs will be nice. Please feel free to add yourself to the list of maintainers in the recipe.

**Comment by stefanv** [comment]
Thanks @bmcfee!

**Comment by bmcfee** [comment]
:shipit: :rocket: thanks!

**Pull request merged**
